# Generated by Django 4.0.3 on 2022-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='square_footage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
